/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainapplication;

import gameobjects.Word;
import gameprocess.GameSession;
import javax.swing.JOptionPane;

/**
 *
 * @author Администратор
 */
public class GameForm extends javax.swing.JFrame {
    
    GameSession currentSession;

    /**
     * Creates new form GameForm
     */
    public GameForm() {
        initComponents();
        this.currentSession = Runner.currentSession;
        
        playerNameLabel.setText(Runner.currentSession.getHumanPlayer().getName());
        
        System.out.println(currentSession.getCurrentPlayerID());
        
        if (currentSession.getCurrentPlayerID() == 1) {
            rulesLabel.setText("<html>Enter the word which is one-letter-different</html>");
            currentSession.firstComputerTurn();
            resultLabel.setText(currentSession.getTurnResult());
            return;
        }
        
        if (currentSession.getCurrentPlayerID() == 2) {
            rulesLabel.setText("<html>Enter any five-letter word</html>");
            resultLabel.setVisible(false);
            return;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerScoreLabel = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        enterWordButton = new javax.swing.JButton();
        newWordField = new javax.swing.JTextField();
        rulesLabel = new javax.swing.JLabel();
        playerNameLabel = new javax.swing.JLabel();
        giveUpButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        gameFormMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);

        playerScoreLabel.setText("Your score: ");

        resultLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resultLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(125, 165, 179), new java.awt.Color(228, 248, 242), new java.awt.Color(178, 207, 207), new java.awt.Color(215, 242, 240)));

        enterWordButton.setText("Enter the word");
        enterWordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterWordButtonActionPerformed(evt);
            }
        });

        rulesLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rulesLabel.setText("<html>Enter the word which is one-letter different</html>");
        rulesLabel.setFocusable(false);

        giveUpButton.setText("Give up");
        giveUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giveUpButtonActionPerformed(evt);
            }
        });

        gameFormMenu.setText("About programm");

        jMenuItem2.setText("Show reference");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        gameFormMenu.add(jMenuItem2);

        jMenuBar1.add(gameFormMenu);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(playerNameLabel)
                .addGap(179, 179, 179))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(giveUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enterWordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newWordField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rulesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                        .addComponent(playerScoreLabel)
                        .addGap(57, 57, 57))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(playerNameLabel)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rulesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerScoreLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(resultLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(newWordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(enterWordButton)
                .addGap(32, 32, 32)
                .addComponent(giveUpButton)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void enterWordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterWordButtonActionPerformed
        resultLabel.setVisible(true);
        resultLabel.setText("");
        rulesLabel.setText("<html>Enter the word which is one-letter-different<html>");
        currentSession.setCurrentPlayer(2);
        Word givenWord = new Word(newWordField.getText());
        currentSession.nextHumanTurn(givenWord);
        playerScoreLabel.setText("Your score: " + currentSession.getScore());
        resultLabel.setText(currentSession.getTurnResult().toString());
        newWordField.setText("");
        
        if (currentSession.isHumanReachedVictory()) {
            rulesLabel.setText("You have won!\n" + rulesLabel.getText().toString());
        }

    }//GEN-LAST:event_enterWordButtonActionPerformed

    private void giveUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giveUpButtonActionPerformed
        JOptionPane.showConfirmDialog(null, new String ("Are you sure that you want to give up?"));
        
        if (JOptionPane.OK_OPTION == 0) {
            this.setVisible(false);
            new ResultForm().setVisible(true);
            currentSession.saveResults();
        }
    }//GEN-LAST:event_giveUpButtonActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GameForm gameForm = new GameForm();
                gameForm.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enterWordButton;
    private javax.swing.JMenu gameFormMenu;
    private javax.swing.JButton giveUpButton;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField newWordField;
    private javax.swing.JLabel playerNameLabel;
    private javax.swing.JLabel playerScoreLabel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JLabel rulesLabel;
    // End of variables declaration//GEN-END:variables
}
