/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainapplication;

import gameobjects.Word;
import gameprocess.GameSession;
import javax.swing.JOptionPane;

/**
 *
 * @author Администратор
 */
public class GameForm extends javax.swing.JFrame {
    
    GameSession currentSession;

    /**
     * Creates new GameForm
     */
    public GameForm() {
        initComponents();
        this.currentSession = Runner.currentSession;
        
        playerNameLabel.setText(Runner.currentSession.getHumanPlayer().getName());
        
        System.out.println(currentSession.getCurrentPlayerID());
        
        if (currentSession.getCurrentPlayerID() == 1) {
            rulesLabel.setText("<html>Введите слово, отличающееся на 1 букву: </html>");
            currentSession.firstComputerTurn();
            resultLabel.setText(currentSession.getTurnResult());
            return;
        }
        
        if (currentSession.getCurrentPlayerID() == 2) {
            rulesLabel.setText("<html>Введите слово, состоящее из 5 букв:</html>");
            resultLabel.setVisible(false);
            return;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerScoreLabel = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        enterWordButton = new javax.swing.JButton();
        newWordField = new javax.swing.JTextField();
        rulesLabel = new javax.swing.JLabel();
        playerNameLabel = new javax.swing.JLabel();
        giveUpButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        gameFormMenu = new javax.swing.JMenu();
        showReferenceMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);

        playerScoreLabel.setText("Your score: ");

        resultLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resultLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(125, 165, 179), new java.awt.Color(228, 248, 242), new java.awt.Color(178, 207, 207), new java.awt.Color(215, 242, 240)));

        enterWordButton.setText("Введите слово");
        enterWordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterWordButtonActionPerformed(evt);
            }
        });

        rulesLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rulesLabel.setText("<html>Enter the word which is one-letter different</html>");
        rulesLabel.setFocusable(false);

        playerNameLabel.setText("Default");

        giveUpButton.setText("Сдаться");
        giveUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giveUpButtonActionPerformed(evt);
            }
        });

        gameFormMenu.setText("О программе");

        showReferenceMenuItem.setText("Показать справку");
        showReferenceMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showReferenceMenuItemActionPerformed(evt);
            }
        });
        gameFormMenu.add(showReferenceMenuItem);

        jMenuBar1.add(gameFormMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(472, Short.MAX_VALUE)
                .addComponent(playerNameLabel)
                .addGap(57, 57, 57)
                .addComponent(playerScoreLabel)
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rulesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(giveUpButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newWordField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(enterWordButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerScoreLabel)
                    .addComponent(playerNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rulesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(resultLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(newWordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(enterWordButton)
                .addGap(32, 32, 32)
                .addComponent(giveUpButton)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void enterWordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterWordButtonActionPerformed
        resultLabel.setVisible(true);
        resultLabel.setText("");
        rulesLabel.setText("<html>Введите слово, отличающееся на 1 букву:<html>");
        currentSession.setCurrentPlayer(2);
        Word givenWord = new Word(newWordField.getText());
        currentSession.nextHumanTurn(givenWord);
        playerScoreLabel.setText("Ваш счёт: " + currentSession.getScore());
        resultLabel.setText(currentSession.getTurnResult().toString());
        newWordField.setText("");
        
        if (currentSession.isHumanReachedVictory()) {
            rulesLabel.setText("<html>Вы победили!</html>" + rulesLabel.getText().toString());
        }

    }//GEN-LAST:event_enterWordButtonActionPerformed

    private void giveUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giveUpButtonActionPerformed
        JOptionPane.showConfirmDialog(null, new String ("Вы уверены, что ходите сдаться?"));
        
        if (JOptionPane.OK_OPTION == 0) {
            this.setVisible(false);
            new ResultForm().setVisible(true);
            currentSession.saveResults();
        }
    }//GEN-LAST:event_giveUpButtonActionPerformed

    private void showReferenceMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showReferenceMenuItemActionPerformed
       ReferenceForm reference = new ReferenceForm();
       reference.setVisible(true);
    }//GEN-LAST:event_showReferenceMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GameForm gameForm = new GameForm();
                gameForm.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enterWordButton;
    private javax.swing.JMenu gameFormMenu;
    private javax.swing.JButton giveUpButton;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField newWordField;
    private javax.swing.JLabel playerNameLabel;
    private javax.swing.JLabel playerScoreLabel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JLabel rulesLabel;
    private javax.swing.JMenuItem showReferenceMenuItem;
    // End of variables declaration//GEN-END:variables
}
